import { Type } from "@google/genai";
import { generateContentWithRetry } from "./client";
import type { CalendarEvent } from "@/lib/google/calendar";

export type EventClassification = "meeting" | "deadline" | "cadence";

const VALID: ReadonlySet<string> = new Set(["meeting", "deadline", "cadence"]);

/**
 * Classify a batch of Google Calendar events in ONE Gemini call so sync stays
 * cheap. Returns a map of event id → classification:
 *   - "cadence":  an event Cadence itself created (work-block phrasing) — skip it.
 *   - "deadline": a due date / submission / exam — decompose into subtasks.
 *   - "meeting":  a scheduled meeting / call / appointment — surface as context only.
 * Index-based (not id-based) so the model never has to echo long opaque ids.
 * Anything unrecognized falls back to "meeting" (the safe, non-destructive default).
 */
export async function classifyCalendarEvents(
  events: CalendarEvent[],
): Promise<Map<string, EventClassification>> {
  const result = new Map<string, EventClassification>();
  if (events.length === 0) return result;

  const list = events
    .map(
      (e, i) =>
        `[${i}] Title: ${e.summary} | When: ${e.start} → ${e.end}` +
        (e.description ? ` | Notes: ${e.description.slice(0, 200)}` : ""),
    )
    .join("\n");

  const prompt = [
    "You are Cadence, a productivity companion. Classify each calendar event into exactly one of:",
    "- cadence: a focused work/study session Cadence created for the user (titles like 'Work on…',",
    "  'Focus: …', 'Prep block', a session tied to one task). These were generated by us — skip them.",
    "- deadline: something due — an assignment, submission, exam, bill, or hard cutoff.",
    "- meeting: a scheduled meeting, call, interview, appointment, or social event with others.",
    "When unsure between meeting and deadline, prefer the one the title most plainly describes.",
    "",
    "Return one entry per event, by its index.",
    "",
    "Events:",
    list,
  ].join("\n");

  const response = await generateContentWithRetry({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            index: { type: Type.INTEGER },
            classification: {
              type: Type.STRING,
              enum: ["meeting", "deadline", "cadence"],
            },
          },
          required: ["index", "classification"],
        },
      },
    },
  });

  let parsed: Array<{ index?: number; classification?: string }> = [];
  try {
    parsed = JSON.parse(response.text ?? "[]");
  } catch {
    // On a malformed response, treat every event as a meeting (safe, non-destructive).
    for (const e of events) result.set(e.id, "meeting");
    return result;
  }

  for (const row of parsed) {
    const idx = Number(row.index);
    const event = events[idx];
    if (!event) continue;
    const cls = String(row.classification);
    result.set(event.id, (VALID.has(cls) ? cls : "meeting") as EventClassification);
  }

  // Any event the model omitted defaults to meeting.
  for (const e of events) if (!result.has(e.id)) result.set(e.id, "meeting");

  return result;
}
