import { Type } from "@google/genai";
import { generateContentWithRetry } from "./client";
import type { CalendarEvent } from "@/lib/google/calendar";

export type EventClassification = "meeting" | "deadline" | "cadence";

const VALID: ReadonlySet<string> = new Set(["meeting", "deadline", "cadence"]);

/**
 * Classify a batch of calendar events + Google Tasks in ONE Gemini call so sync
 * stays cheap. Returns a map of id → classification:
 *   - "cadence":  an event Cadence itself created (work-block phrasing) — skip it.
 *   - "deadline": a due date / submission / exam — decompose into subtasks.
 *   - "meeting":  a scheduled meeting / call / appointment — surface as context only.
 * Birthday-calendar events are forced to "meeting" in code (never sent to the model).
 * Index-based (not id-based) so the model never has to echo long opaque ids.
 * Anything unrecognized falls back to "meeting" (the safe, non-destructive default).
 */
export async function classifyCalendarEvents(
  events: CalendarEvent[],
): Promise<Map<string, EventClassification>> {
  const result = new Map<string, EventClassification>();
  if (events.length === 0) return result;

  // Birthdays are always context-only — force "meeting" and never spend a model slot.
  const toClassify: CalendarEvent[] = [];
  for (const e of events) {
    if (e.isBirthday) result.set(e.id, "meeting");
    else toClassify.push(e);
  }
  if (toClassify.length === 0) return result;

  const list = toClassify
    .map((e, i) => {
      const tag = e.source === "google_task" ? "[Google Task] " : "";
      return (
        `[${i}] ${tag}Title: ${e.summary} | When: ${e.start} → ${e.end}` +
        (e.description ? ` | Notes: ${e.description.slice(0, 200)}` : "")
      );
    })
    .join("\n");

  const prompt = [
    "You are Cadence, a productivity companion. Classify each item into exactly one of:",
    "- cadence: a focused work/study session Cadence created for the user (titles like 'Work on…',",
    "  'Focus: …', 'Prep block', a session tied to one task). These were generated by us — skip them.",
    "- deadline: something due — an assignment, submission, exam, bill, or hard cutoff.",
    "- meeting: a scheduled meeting, call, interview, appointment, birthday, or social event.",
    "When unsure between meeting and deadline, prefer the one the title most plainly describes.",
    "Items marked [Google Task] are Google Tasks — these are almost always a deadline.",
    "Birthdays and anniversaries are meeting (context only), never a deadline.",
    "",
    "Return one entry per item, by its index.",
    "",
    "Items:",
    list,
  ].join("\n");

  const response = await generateContentWithRetry({
    model: "gemini-2.5-flash",
    contents: prompt,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            index: { type: Type.INTEGER },
            classification: {
              type: Type.STRING,
              enum: ["meeting", "deadline", "cadence"],
            },
          },
          required: ["index", "classification"],
        },
      },
    },
  });

  let parsed: Array<{ index?: number; classification?: string }> = [];
  try {
    parsed = JSON.parse(response.text ?? "[]");
  } catch {
    // On a malformed response, treat every remaining item as a meeting (safe default).
    for (const e of toClassify) result.set(e.id, "meeting");
    return result;
  }

  for (const row of parsed) {
    const idx = Number(row.index);
    const event = toClassify[idx];
    if (!event) continue;
    const cls = String(row.classification);
    result.set(event.id, (VALID.has(cls) ? cls : "meeting") as EventClassification);
  }

  // Any item the model omitted defaults to meeting.
  for (const e of toClassify) if (!result.has(e.id)) result.set(e.id, "meeting");

  return result;
}
